# Generated by Django 4.2.1 on 2023-05-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUsers', '0002_alter_tuser_modified_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='modified_time',
            field=models.DateTimeField(default='05/26/2023 09:44 18 PM'),
        ),
    ]
